# Generated by Django 3.0.4 on 2020-03-18 07:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя Автора')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия Автора')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата Рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата Смерти')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название книги', max_length=300, verbose_name='Название Книги')),
                ('summary', models.TextField(help_text='Введите описание книги', max_length=1000, verbose_name='Описание книги')),
                ('isbn', models.CharField(help_text='13 значный Международный стандартный книжный номер  <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>"', max_length=13, verbose_name='ISBN')),
                ('author', models.ForeignKey(help_text='Автор', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author', verbose_name='Авторы Книги')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название жанра', max_length=200, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID книги внутри библиотеки', primary_key=True, serialize=False, verbose_name='Уникальный ID')),
                ('imprint', models.CharField(max_length=200, verbose_name='ХЗ че')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Дата появления')),
                ('status', models.CharField(blank=True, choices=[('m', 'На обслуживании'), ('o', 'В Аренде'), ('a', 'Доступна'), ('r', 'Зарезервирована')], default='m', help_text='Book availability', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book', verbose_name='Наменование Книги')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Выберите жанр для книги', to='catalog.Genre'),
        ),
    ]
